apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-python-chart.fullname" . }}-config
  labels:
    {{- include "charts-app-python.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ .Files.Get "files/config.json" | nindent 4 }}
