apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    app: charts-app-python
    {{- include "charts-app-python.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
