---
- name: Wipe data
  tags: ["time_app_wipe"]
  block:
    - name: Wipe docker compose services
      community.docker.docker_compose:
        project_src: "{{ web_app_path }}"
        state: absent
        remove_volumes: true
      ignore_errors: true

    - name: Wipe a base path
      ansible.builtin.file:
        path: "{{ web_app_path }}"
        state: absent
