---
- name: Include wipe if needed
  ansible.builtin.include_tasks: 0-wipe.yml
  when: web_app_full_wipe | bool
  tags: [ "time_app", "time_app_wipe" ]

- name: Deploy time app
  tags: [ "time_app" ]
  block:
    - name: Create a directory of application
      ansible.builtin.file:
        path: "{{ web_app_path }}"
        state: directory
        mode: '0755'

    - name: Docker compose file creation
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{web_app_path}}/docker-compose.yml"
        owner: root
        group: root
        mode: '600'

    - name: Run all services
      community.docker.docker_compose:
        project_src: "{{web_app_path}}"
        state: present
        pull: true
