version: '3'

x-logging: &logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}"
    max-size: "200k"
    max-file: "10"

services:

  app_python:
    image: smorenapi/app_python:latest
    ports:
      - "8000:8000"
    networks:
      - app_python
      - monitoring
    logging: *logging

  app_kotlin:
    image: smorenapi/app_kotlin:latest
    ports:
      - "8080:8080"
    networks:
      - app_kotlin
      - monitoring
    logging: *logging

  loki:
    image: grafana/loki:2.6.1
    expose:
      - 3100
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    logging: *logging

  promtail:
    image: grafana/promtail:2.6.1
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - app_python
      - app_kotlin
      - monitoring
    logging: *logging

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ${PWD}/loki.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging: *logging

networks:
  app_python: { }
  app_kotlin: { }
  monitoring: { }

volumes:
  grafana-data: { }
  loki-data: { }
  promtail-data: { }
