---
- name: Check python3-pip installation
  become: true
  package:
    name: "python3-pip"
    state: present

- name: Install docker libraries
  pip:
    name:
      - docker=={{ docker_version }}
      - docker-compose=={{ python_docker_compose_version }}
    state: present
