name: Kotlin CI

on: [ push, pull_request ]

jobs:

  changes:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      app_kotlin: ${{ steps.filter.outputs.app_kotlin }}
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app_kotlin:
              - 'app_kotlin/**'

  build:
    if: ${{ needs.changes.outputs.app_kotlin == 'true' }}
    needs: [ changes ]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Execute Gradle build
        run: |
          cd app_kotlin
          gradle build

  security:
    if: ${{ needs.changes.outputs.app_kotlin == 'true' }}
    needs: [ build ]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        run: |
          cd app_kotlin
          snyk test --all-projects --sarif-file-output=result.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: app_kotlin/result.sarif

  publish-image:
    if: ${{ needs.changes.outputs.app_kotlin == 'true' }}
    needs: [ security ]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app_kotlin
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app_kotlin:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/app_kotlin:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/app_kotlin:buildcache,mode=max
